name: Python Tests

on:
  push:
    branches:
      - basic-update
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip" # Kích hoạt cache cho pip

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip        # Cache pip packages
            .venv              # Cache virtual env
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          cd vehicle_detection
          pytest
